# ---------- Build Stage ----------
FROM node:22 AS builder

WORKDIR /app

# Copy only the frontend project first
COPY frontend/package*.json ./

RUN npm install

COPY frontend/ .

RUN npm run build


# ---------- Production Stage ----------
FROM nginx:latest

# Copy the built React application
COPY --from=builder /app/dist /usr/share/nginx/html

# Use our custom Nginx configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]